name: Bilan Ferry Quotidien

on:
  workflow_dispatch: # <--- Cette ligne magique active le bouton gris "Run workflow" !
  schedule:
    - cron: '0 8 * * *'
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les outils (Playwright)
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Lancer le script de recherche
        run: python script_ferry.py
